### ISSUE TITLE
Invalid Weight Modification

### ISSUE THREAD

**Issue by SeanChengN** [SuperScary/Heavy-Inventories#1]
I had tested some goods, like"iron_sword".
![2](https://user-images.githubusercontent.com/20624068/53078165-979e1c00-352e-11e9-8b26-82b8129310c5.png)
But the weight is no-change.
![1](https://user-images.githubusercontent.com/20624068/53078182-a2f14780-352e-11e9-922a-615523b8d602.png)
And some goods is changed, like"trapdoor".
![4](https://user-images.githubusercontent.com/20624068/53078200-ac7aaf80-352e-11e9-9822-2353966d318d.png)

**Comment by SuperScary** [comment]
Fixed in push [92f800c](https://github.com/SuperScary/Heavy-Inventories/commit/92f800c1f786688468b2de625e61542529f13f47)

Heavy Inventories v2.3.3
