### ISSUE TITLE
Crash when over weight running/climbing

### ISSUE THREAD

**Issue by SeanChengN** [SuperScary/Heavy-Inventories#11]
I don't know if it is the same as this one: https://github.com/SuperScary/Heavy-Inventories/issues/8
Reports1: https://paste.dimdev.org/loqanageqi.makefile
Reports2: https://paste.dimdev.org/caturufade.rb

**Comment by SuperScary** [comment]
whoops. looks like i’m firing a Toast on the server side as well as the client side. should be an easy fix. thanks for catching that.
