### ISSUE TITLE
Incompatible with Baubles 

### ISSUE THREAD

**Issue by lelodragneel** [SuperScary/Heavy-Inventories#14]
Using latest version of Heavy Inventories and Baubles.

Server starts up with no problems. As soon as I join the game, the client attempts to login but it disconnects me and spits a long error message. The server remains online though. 

Here's the error message:
https://pastebin.com/YeTkmUgc

**Comment by SuperScary** [comment]
Should be fixed in build 2.2.2-1

**Comment by lelodragneel** [comment]
Issue persists.
