### ISSUE TITLE
Enhancement suggestion

### ISSUE THREAD

**Issue by BitBork** [SuperScary/Heavy-Inventories#3]
Would it be possible to implement an item or potion into this mod that disables the weight either indefinately (when holding the item) or temporarily (with a potion)? I thought of this because this mod certainly adds more immersiveness to mc, but it makes building a pain, since when you're building on a large scale you'd be limited to carrying x blocks.

Also I'd very much like a neater gui, instead of a number next to the toolbar. I was thinking of a small weight icon that fills up/empties with increased/lowered weight, changes colour according to weight, and then have the exact number displayed in the inventory? (simple example: https://imgur.com/a/mON78)

**Comment by SuperScary** [comment]
Added
