### ISSUE TITLE
Doesn't support items registered by non-existant mods

### ISSUE THREAD

**Issue by DaMatrix** [SuperScary/Heavy-Inventories#8]
Hi! I'm a developer on Valkyrien Warfare. We've recently received issue https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/issues/141 , which seems to be caused by https://github.com/SuperScary/Heavy-Inventories/blob/master/src/main/java/superscary/heavyinventories/util/Toolkit.java#L44-L55 returning null. The reason for this is that we use an addon system that registers items using the addon's name, not the mod's actual name. Therefore there will never be a mod named `valkyrienwarfarecontrol` (for example), as the item was registered by `valkyrienwarfare`. (see https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/blob/master/src/main/java/valkyrienwarfare/addon/control/ValkyrienWarfareControl.java#L137-L166 ).

Is there a reason you're not simply getting the mod name from the item's registry name (i.e. calling `block.getRegistryName().getResourceDomain()`)?  You're kinda hacking around by calling `getRegistryName().toString()` (see https://github.com/Creeperface01/MinecraftSource/blob/master/src/net/minecraft/util/ResourceLocation.java#L61 ), because that just combines the two names and then you split them again (see https://github.com/SuperScary/Heavy-Inventories/blob/master/src/main/java/superscary/heavyinventories/util/Toolkit.java#L46 ).

Thanks!

**Comment by SuperScary** [comment]
REviewed and fixed. Thanks!
