### ISSUE TITLE
The weight file can't be read again

### ISSUE THREAD

**Issue by SeanChengN** [SuperScary/Heavy-Inventories#9]
Mod version: 2.4
The weight of all items have become 0.1 stone.

**Comment by SuperScary** [comment]
I am unable to recreate this issue. Are all modded items now registering as 0.1 or is it just minecraft items/blocks? Minecraft items and blocks are now handled the same as a mod. 

With any item in the players hand, issue the command /heavyinventories set 0.5  This should set the item weight in game without the need to modify it within the config files (should you so choose, but modifying item weights within the config files should also work).

**Comment by SeanChengN** [comment]
Just minecraft items/blocks, I have not set the weight of other modded items.
This file was generated by the old version, You can use the file to test.
[Minecraft.zip](https://github.com/SuperScary/Heavy-Inventories/files/2977063/Minecraft.zip)

**Comment by SuperScary** [comment]
So the old class that was used to create minecraft weights is no longer used. the weights should have defaulted to 0.1 if a custom weight wasn’t set

**Comment by SeanChengN** [comment]
Well, If I set "autoGenerateWeightConfigFiles=true", the file can be read...

**Comment by SuperScary** [comment]
interesting. i’ll look into it
